# -*- coding: utf-8 -*-
"""p119

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TlnC3b7IjAMqXv51LbzWyN4gxFZneO8g
"""

from google.colab import files
data_to_load=files.upload()

import pandas as pd
col_names=['PassengerId','Pclass','Sex,Age','SibSp','Parch','Survived']
df=pd.read_csv("data.csv",names=col_names).iloc[1:]
print(df.head())

features=['PassengerId','Pclass','Sex,Age','SibSp','Parch','Survived']
X=df[features]
Y=df.Survived

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=1)
clf=DecisionTreeClassifier()
clf=clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
print("accuracy: ",metrics.accuracy_score(y_test,y_pred))

from sklearn.tree import export_graphviz
from six import StringIO 
from IPython.display import Image
import pydotplus

dot_data = StringIO() #Where we will store the data from our decision tree classifier as text.

export_graphviz(clf, out_file=dot_data, filled=True, rounded=True, special_characters=True, feature_names=features, class_names=['0','1'])

print(dot_data.getvalue())

graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png('diabetes.png')
Image(graph.create_png())

clf = DecisionTreeClassifier(max_depth=3)

clf = clf.fit(x_train,y_train)

y_pred = clf.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

dot_data = StringIO() #Where we will store the data from our decision tree classifier as text.

export_graphviz(clf, out_file=dot_data, filled=True, rounded=True, special_characters=True, feature_names=features, class_names=['0','1'])

graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png('diabetes.png')
Image(graph.create_png())